# Generated by Django 2.1.3 on 2019-01-08 17:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_import_data.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('auditee_fields', django.contrib.postgres.fields.jsonb.JSONField(encoder=django_import_data.models.DjangoErrorJSONEncoder, null=True)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(encoder=django_import_data.models.DjangoErrorJSONEncoder, null=True)),
                ('error_summary', django.contrib.postgres.fields.jsonb.JSONField(encoder=django_import_data.models.DjangoErrorJSONEncoder, null=True)),
                ('status', models.CharField(choices=[('rejected', 'Rejected: Fatal Errors'), ('created_dirty', 'Imported: Some Errors'), ('created_clean', 'Imported: No Errors'), ('pending', 'Pending')], default='pending', max_length=16)),
                ('imported_from', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericAuditGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('rejected', 'Rejected: Fatal Errors'), ('created_dirty', 'Imported: Some Errors'), ('created_clean', 'Imported: No Errors'), ('pending', 'Pending')], default='pending', max_length=16)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='genericaudit',
            name='audit_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='django_import_data.GenericAuditGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='genericauditgroup',
            unique_together={('content_type', 'object_id')},
        ),
    ]
