# Generated by Django 2.1.5 on 2019-02-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimportattempt',
            name='imported_by',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
