# Generated by Django 2.2.2 on 2019-06-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimportattempt',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'created_clean'), (2, 'created_dirty'), (3, 'rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='fileimportbatch',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'created_clean'), (2, 'created_dirty'), (3, 'rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='fileimporter',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'created_clean'), (2, 'created_dirty'), (3, 'rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='modelimportattempt',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'created_clean'), (2, 'created_dirty'), (3, 'rejected')], default=0),
        ),
    ]
