# Generated by Django 2.1.5 on 2019-02-05 19:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0002_fileimportattempt_imported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowdata',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
