# Generated by Django 2.2.2 on 2019-06-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0002_auto_20190618_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileimportattempt',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fileimportbatch',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fileimporter',
            name='status',
        ),
    ]
