# Generated by Django 2.1.5 on 2019-02-08 00:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0004_rowdata_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimportattempt',
            name='ignored_headers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, help_text='Headers that were ignored during import', null=True, size=None),
        ),
    ]
