# Generated by Django 2.1.5 on 2019-02-11 23:16

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0005_fileimportattempt_ignored_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImportBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created_clean', 'Imported: No Errors'), ('created_dirty', 'Imported: Some Errors'), ('rejected', 'Rejected: Fatal Errors')], default='pending', max_length=13)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('command', models.CharField(default=None, max_length=64)),
                ('args', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('kwargs', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'File Import Batch',
                'verbose_name_plural': 'File Import Batches',
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='fileimportattempt',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fileimporter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelimportattempt',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fileimportattempt',
            name='file_import_batch',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='file_import_attempts', to='django_import_data.FileImportBatch'),
            preserve_default=False,
        ),
    ]
