# Generated by Django 2.1.5 on 2019-02-14 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0006_file_import_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileimportbatch',
            name='is_active',
        ),
    ]
