# Generated by Django 2.2.2 on 2019-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0006_auto_20190702_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimportattempt',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='fileimportbatch',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='fileimporter',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
