# Generated by Django 2.1.5 on 2019-02-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0007_remove_fileimportbatch_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileimportattempt',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='fileimporter',
            name='is_active',
        ),
    ]
