# Generated by Django 2.2.2 on 2019-07-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0007_auto_20190702_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileimportattempt',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='fileimportbatch',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='fileimporter',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='modelimportattempt',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='fileimportattempt',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'empty'), (2, 'deleted'), (3, 'created_clean'), (4, 'created_dirty'), (5, 'rejected')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='fileimportbatch',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'empty'), (2, 'deleted'), (3, 'created_clean'), (4, 'created_dirty'), (5, 'rejected')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='fileimporter',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'empty'), (2, 'deleted'), (3, 'created_clean'), (4, 'created_dirty'), (5, 'rejected')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='modelimportattempt',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'empty'), (2, 'deleted'), (3, 'created_clean'), (4, 'created_dirty'), (5, 'rejected')], db_index=True, default=0),
        ),
    ]
