# Generated by Django 2.1.5 on 2019-02-15 18:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0008_auto_20190214_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimportbatch',
            name='errors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
