# Generated by Django 2.2.2 on 2019-07-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0008_auto_20190702_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelimportattempt',
            name='acknowledged',
        ),
    ]
