# Generated by Django 2.2.2 on 2019-07-05 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0011_auto_20190705_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelimporter',
            name='file_import_attempt',
            field=models.ForeignKey(blank=True, help_text='Reference to the FileImportAttempt this was created from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_importers', to='django_import_data.FileImportAttempt'),
        ),
    ]
