# Generated by Django 2.2.2 on 2019-07-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0012_auto_20190705_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileImportBatch',
            new_name='FileImporterBatch',
        ),
        migrations.RemoveField(
            model_name='fileimportattempt',
            name='file_import_batch',
        ),
        migrations.AddField(
            model_name='fileimporter',
            name='file_importer_batch',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='file_import_attempts', to='django_import_data.FileImporterBatch'),
            preserve_default=False,
        ),
    ]
