# Generated by Django 2.2.2 on 2019-07-05 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0013_auto_20190705_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimporter',
            name='file_importer_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_importers', to='django_import_data.FileImporterBatch'),
        ),
    ]
