# Generated by Django 2.2.2 on 2019-07-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0014_auto_20190705_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileimporterbatch',
            options={'ordering': ['-created_on'], 'verbose_name': 'File Importer Batch', 'verbose_name_plural': 'File Importer Batches'},
        ),
        migrations.AlterField(
            model_name='fileimporter',
            name='file_importer_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_importers', to='django_import_data.FileImporterBatch'),
        ),
        migrations.AlterField(
            model_name='modelimporter',
            name='file_import_attempt',
            field=models.ForeignKey(default=-1, help_text='Reference to the FileImportAttempt this was created from', on_delete=django.db.models.deletion.CASCADE, related_name='model_importers', to='django_import_data.FileImportAttempt'),
            preserve_default=False,
        ),
    ]
