# Generated by Django 2.2.2 on 2019-07-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0015_auto_20190705_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelimporter',
            name='file_import_attempt',
        ),
        migrations.AddField(
            model_name='modelimporter',
            name='row_data',
            field=models.ForeignKey(default=-1, help_text='Reference to the original data used to create this audit group', on_delete=django.db.models.deletion.CASCADE, related_name='model_importers', to='django_import_data.RowData'),
            preserve_default=False,
        ),
    ]
