# Generated by Django 2.2.2 on 2019-07-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0016_auto_20190708_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowdata',
            name='file_import_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_datas', to='django_import_data.FileImportAttempt'),
        ),
    ]
