# Generated by Django 2.2.2 on 2019-07-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0017_auto_20190708_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelimportattempt',
            name='row_data',
        ),
    ]
