# Generated by Django 2.2.2 on 2019-07-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0018_remove_modelimportattempt_row_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowdata',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'empty'), (2, 'deleted'), (3, 'created_clean'), (4, 'created_dirty'), (5, 'rejected')], db_index=True, default=0),
        ),
    ]
